### ISSUE TITLE
File.downloadが正しく動作しません

### ISSUE THREAD

**Issue by moongift** [NIFTYCloud-mbaas/ncmb_js#143]
res.bodyにbufferが入ってきます。なので、request.jsの_callbackにおいて、

```
var body = (typeof res.text == 'undefined' && res.body) ? res.body : res.text;
return (callback && callback(null, body)) || resolve(body, res);
```

といった感じになっていないと res.text = undefined が返ってきます。

**Comment by fuku2015** [comment]
返信遅くなりましたが、ご報告ありがとうございます！
サーバサイド環境にてご指摘いただいたとおりの挙動が確認できました。
次回アップデートにて対応させていただきます。

**Comment by fuku2015** [comment]
v2.1.2で対応済みなのでクローズします。
