### ISSUE TITLE
ファイルアップロード時にmime-typeが正しくセットされません

### ISSUE THREAD

**Issue by moongift** [NIFTYCloud-mbaas/ncmb_js#150]
https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/request.js#L131

のところを

```
r.attach("file", file.fileData, file.fileName);
```

とするとファイル名に応じてセットしてくれるようになります。

**Comment by fuku2015** [comment]
こちらもご報告ありがとうございます！
サーバサイド環境にてご指摘いただいたとおりの挙動が確認できました。
次回アップデートにて対応させていただきます。

**Comment by fuku2015** [comment]
v2.1.2で対応済みなのでクローズします。
