### ISSUE TITLE
メールで会員ログインし、会員情報を更新するとmailAddressConfirmがfalseになってしまいます

### ISSUE THREAD

**Issue by ncmbadmin** [NIFTYCloud-mbaas/ncmb_js#152]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version): Javascript SDK v.2.1.1
- 不具合が発生した環境(Environment requirement): NodeJS + Monaca
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)

```javascript
	ncmb.User.requestSignUpEmail("abc@gmail.com")
	         .then(function(data){
	            // 送信後処理
	            console.log("Updated done")
	         })
	         .catch(function(err){
	           // エラー処理
	           console.log(JSON.stringify(err));
	         });
```

ユーザ更新

```javascript
	//Userのインスタンスを作成
	var user = new ncmb.User();
	// メールアドレスとパスワードでログイン
	ncmb.User.loginWithMailAddress("abc@gmail.com", "test")
             .then(function(user){
			    	console.log("Login successfull");
			        // ログイン後処理
			        var currentUser = ncmb.User.getCurrentUser();
					user.set("new", "newvalue");
					user.update()
					    .then(function(obj){
				            // 保存後の処理
				            console.log("Updated done")
				         })
				        .catch(function(err){
				            // エラー処理
				            console.log("Update error: " +JSON.stringify(err));
				        });
			    })
			    .catch(function(err){
			      // エラー処理
			    });
```

- エラーメッセージ(Error messages)
エラーが出なく、ユーザ更新は正常行いましたが、ユーザの「mailAddressConfirm」 がtrue -> falseになって、ログインができなくなっています。

**Comment by fuku2015** [comment]
v2.1.2で対応済みなのでクローズします。
