### ISSUE TITLE
Firefox v48.0でAPIリクエストを行なうとシグネチャエラーが返却される

### ISSUE THREAD

**Issue by n0guch1** [NIFTYCloud-mbaas/ncmb_js#162]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
 - v2.1.2
- 不具合が発生した環境(Environment requirement)
 - Firefox v48.0 (Safari,Chrome,IE,Firefox47.0では正常に動作)
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
 - クイックスタート実施
- エラーメッセージ(Error messages)
 - `{"code":"E403002","error":"Unauthorized operations for signature."}`

リクエストヘッダーに追加したシグネチャの「=」の後に不正な値が入っている模様
`X-NCMB-Signature : 6rH+sM6DVo3C/u62JiRnL61YnXT15twvbcvjtS+Ez2Q=z2QAAAAA`

**Comment by ncmbsdk** [comment]
ご迷惑をおかけすることになり、誠に申し訳ございませんでした。
v2.1.3で対応が完了したのでクローズします。
