### ISSUE TITLE
ドキュメントの修正

### ISSUE THREAD

**Issue by FukMo10** [NIFTYCloud-mbaas/ncmb_js#169]
## 不具合の概要(Description of bug)
- ドキュメントが実装と異なっている
- 実装の合わせてドキュメントを修正
  1. [Relation.prototype.add](https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/relation.js#L33)
     - × addRelation
     - 〇 add
  2. [Relation.prototype.remove](https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/relation.js#L41)
     - × removeRelation
     - 〇 remove
  3. [Query.prototype.exists](https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/query.js#L144)
     - × exist
     - 〇 exists

**Comment by ykokw** [comment]
query.jsのexistsメソッドの説明文を追加で修正する
> valueにfalseが設定されている場合、指定したキーに値が存在しないオブジェクトを検索します。
s/value/exists/
