### ISSUE TITLE
[Read Me] v1保守期限追記

### ISSUE THREAD

**Issue by fuku2015** [NIFTYCloud-mbaas/ncmb_js#88]

**Comment by Rebirthble** [comment]
- ついでにLICENSEも追加しましょう！
 - https://github.com/NIFTYCloud-mbaas/ncmb_ios
 - ReadmeにてLICENSEファイルを見てもらうようにする
 - LICENSEファイルを用意する

**Comment by Rebirthble** [comment]
これちょっと再検討させてもらえないですか

**Comment by fuku2015** [comment]
保守期限についてはドキュメントに明記したので、こちらはクローズします。
